# Generated by Django 3.2.10 on 2022-02-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placecomuser',
            old_name='name',
            new_name='place_user_name',
        ),
    ]
