# Generated by Django 3.2.12 on 2022-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220308_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='CS', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(default='B Tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sap_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=4),
        ),
    ]
