# Generated by Django 3.2.12 on 2022-03-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='role_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.jd'),
            preserve_default=False,
        ),
    ]
