# Generated by Django 3.2.12 on 2022-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_mcq_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_skills',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
