# Generated by Django 3.2.12 on 2022-03-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_mcq_skills_activated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mcq_Skills',
        ),
    ]
