# Generated by Django 3.2.12 on 2022-03-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_event_role_id'),
        ('home', '0017_auto_20220317_1602'),
    ]

    operations = [
    ]
