# Generated by Django 3.2.12 on 2022-03-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_0014_event_role_id_0017_auto_20220317_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='placed_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('jd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jd')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
