# Generated by Django 3.2.12 on 2022-03-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0002_ques_ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ques_ans',
        ),
    ]
