# Generated by Django 3.2.12 on 2022-03-13 06:11
# Generated by Django 3.2.12 on 2022-03-13 07:17

import csvs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='csvs', validators=[csvs.validators.validate_file_extension]),
        ),
    ]
